services:
  bedrock-proxy-endpoint:
    image: bedrock-proxy-endpoint
    ports:
      - "80:80"
      - "443:443"
    environment:
      CONSOLE_LOGGING: "false"
      HTTP_ENABLED: "true"
      HTTP_PORT: "80"
      HTTPS_ENABLED: "false"
      HTTPS_PORT: "443"
      HTTPS_KEY_PATH: "./some-path/mykey.key"
      HTTPS_CERT_PATH: "./some-path/mycert.pem"
      IP_RATE_LIMIT_ENABLED: "true"
      IP_RATE_LIMIT_WINDOW_MS: "60000"
      IP_RATE_LIMIT_MAX_REQUESTS: "100"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
